# Generated by Django 5.2.17 on 2026-09-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer full name', max_length=200)),
                ('phone', models.CharField(help_text='Customer phone number', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Customer email address (optional)', max_length=254, null=True)),
                ('location', models.CharField(blank=True, help_text='Customer location or city', max_length=200, null=True)),
                ('enquiry_type', models.CharField(choices=[('General Enquiry', 'General Enquiry'), ('Product Enquiry', 'Product Enquiry'), ('Project Requirement', 'Project Requirement'), ('Bulk Requirement', 'Bulk Requirement'), ('Other', 'Other')], default='General Enquiry', help_text='Category of enquiry', max_length=50)),
                ('message', models.TextField(help_text='Detailed project requirement or message')),
                ('is_contacted', models.BooleanField(default=False, help_text='Status flag indicating whether company sales/support team has followed up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Enquiry',
                'verbose_name_plural': 'Contact Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
