# Generated by Django 5.2.17 on 2026-09-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title (required, up to 250 characters)', max_length=250)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL identifier. Auto-generated from title if left blank.', max_length=255, unique=True)),
                ('excerpt', models.CharField(blank=True, default='', help_text='Brief summary for listings, cards, and previews (recommended 150-300 characters)', max_length=500)),
                ('content', models.TextField(help_text='Main article content in plain text or structured paragraphs.')),
                ('featured_image', models.ImageField(blank=True, help_text='Optional featured header/card image. Blog works completely without an image.', null=True, upload_to='blog/')),
                ('author_name', models.CharField(blank=True, default='Classic Mun Bricks', help_text="Author name or entity (defaults to 'Classic Mun Bricks')", max_length=120)),
                ('seo_title', models.CharField(blank=True, default='', help_text='Optional custom SEO title tag. If left blank, the main title will be used.', max_length=250)),
                ('meta_description', models.CharField(blank=True, default='', help_text='Optional SEO meta description for search engines (recommended ~160 characters)', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', help_text='Only published posts are visible on the public website.', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Official publication date and time. Set automatically on first publish if left blank.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the post was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the post was last edited')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
