# Generated by Django 5.2.17 on 2026-08-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Sequence order of the manufacturing process (e.g. 1 for Process 01)', unique=True)),
                ('title', models.CharField(help_text="Process title, e.g. 'Initial Material Processing'", max_length=200)),
                ('short_description', models.TextField(help_text='Factual description of this manufacturing stage')),
                ('image', models.CharField(blank=True, help_text='Image asset filename or static path', max_length=500, null=True)),
                ('video', models.CharField(blank=True, help_text='Video asset filename or static path', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility in the virtual factory tour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factory Process',
                'verbose_name_plural': 'Factory Processes',
                'ordering': ['step_number'],
            },
        ),
    ]
