# Generated by Django 5.2.17 on 2026-09-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Classic Mun Bricks', max_length=200)),
                ('about_short', models.TextField(default='Classic Mun Bricks is a premier brick manufacturer based in Kerala, serving major construction and architectural projects across Kerala and Tamil Nadu.')),
                ('about_long', models.TextField(default='Built on practical experience, raw clay purity, and high-density extrusion technology, Classic Mun Bricks delivers engineered structural bricks crafted for lasting durability.')),
                ('tamil_nadu_projects', models.PositiveIntegerField(default=2000, help_text='Verified completed projects count in Tamil Nadu (e.g. 2000+)')),
                ('kerala_projects', models.PositiveIntegerField(default=1500, help_text='Verified completed projects count in Kerala (e.g. 1500+)')),
                ('total_projects', models.PositiveIntegerField(default=3500, help_text='Combined verified completed projects across Kerala + Tamil Nadu (e.g. 3500+)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
    ]
