# Generated by Django 5.2.17 on 2026-09-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='started_year',
            field=models.PositiveIntegerField(default=2006, help_text='Company founding year (2006)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='years_experience',
            field=models.PositiveIntegerField(default=20, help_text='Years of manufacturing experience (20 years)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='about_long',
            field=models.TextField(default='Classic Mun Bricks has been serving construction projects across Kerala and Tamil Nadu for 20 years. Our experience comes from thousands of completed projects across both states.'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='about_short',
            field=models.TextField(default='Since 2006, Classic Mun Bricks has served projects across Kerala and Tamil Nadu.'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='kerala_projects',
            field=models.PositiveIntegerField(default=1500, help_text='Verified completed projects count in Kerala (1.5K+)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tamil_nadu_projects',
            field=models.PositiveIntegerField(default=1000, help_text='Verified completed projects count in Tamil Nadu (1K+)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='total_projects',
            field=models.PositiveIntegerField(default=2500, help_text='Combined verified completed projects across Kerala + Tamil Nadu (2.5K+)'),
        ),
    ]
